# APP
spring:
  application:
    name: 'portfolio-admin'
  profiles:
    active:
      - local
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 70MB

# SERVER
server:
  servlet:
    context-path: '/portfolio/admin/v1'

# APPLICATION
app:
  firebase:
    auth-file: admin-sdk.json
    database-url: ${DB_URL}
    storage-url: ${STORAGE_URL}
