# SPRING
spring:
  application:
    name: 'portfolio-admin'
  profiles:
    active:
      - local
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 70MB

# SPRING DOC
springdoc:
  api-docs:
    version: OPENAPI_3_0
  swagger-ui:
    use-root-path: true

# SERVER
server:
  servlet:
    context-path: '/portfolio/admin/v1'

# APPLICATION
app:
  firebase:
    auth-file: admin-sdk.json
    database-url: ${DB_URL}
    storage-url: ${STORAGE_URL}
  swagger:
    version: 0.0.1
    title: 'Portfolio Admin API'
    description: 'API to create update data for personal portfolio'
