---
name: Lint

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4.10.1
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*src/.*

          VALIDATE_JAVA: true
          VALIDATE_YAML: true
