name: Tests

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - name: Gradle build
        run: ./gradlew test
